<?php

function dna_find_pair($input) {
    if ($input == 'A') {
        return 'T';
    } elseif ($input == 'T') {
        return 'A';
    } elseif ($input == 'C') {
        return 'G';
    } elseif ($input == 'G') {
        return 'C';
    } else {
        return ' ';
    }
}

function dna_find_strand($input) {
    $input_array = str_split($input);
    $output_array = array();
    foreach ($input_array as $input_letter) {
        if (preg_match('/[ATCG ]/', $input_letter)) {
            $output_array[] = dna_find_pair($input_letter);
        }
    }
    return join('', $output_array);
}
