<?php

function dna_menu() {
    $items['dna'] = array(
        'title' => 'DNA Strand Translator',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function dna_form() {
    $form['input_strand'] = array(
        '#title' => 'Input Strand',
        '#type' => 'textfield',
        '#description' => t('Enter the strand to translate'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Translate',
    );
    return $form;
}

function dna_find_pair($input) {
    if ($input == 'A') {
        return 'T';
    } elseif ($input == 'T') {
        return 'A';
    } elseif ($input == 'C') {
        return 'G';
    } elseif ($input == 'G') {
        return 'C';
    } else {
        return ' ';
    }
}

function dna_find_strand($input) {
    $input_array = str_split($input);
    $output_array = array();
    foreach ($input_array as $input_letter) {
        if (preg_match('/[ATCG ]/', $input_letter)) {
            $output_array[] = dna_find_pair($input_letter);
        }
    }
    return join('', $output_array);
}
