<?php

function dna_facts_menu() {
    $items['dna-facts/%/%'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'dna_facts_ajax_callback',
        'page arguments' => array(1,2),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_facts_ajax_callback($js, $node_id) {
    $node = node_load($node_id);
    if ($js == 'nojs') {
      drupal_goto('node/' . $node->nid);
    }
    $build = node_view($node);
    $html = render($build);
    $commands = array();
    $commands[] = ajax_command_html('#dna-facts-ajax-wrapper', $html);
    print ajax_render($commands);
    exit;
}
